name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Remove Frozen Mode
        run: bundle config set --local frozen false
      - name: Install Required Gems
        run: |
          echo "gem 'csv'" >> Gemfile
          echo "gem 'base64'" >> Gemfile
          echo "gem 'logger'" >> Gemfile
          bundle install

      - name: Install Gems
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
