name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      # Debugging environment
      - name: Print environment details
        run: |
          echo "Ruby version:"
          ruby --version
          echo "Bundler version:"
          bundler --version
          echo "Working directory:"
          pwd
          echo "Contents of workspace:"
          ls -la

      # Cache Ruby gems
      - name: Cache gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Install dependencies
      - name: Install dependencies
        run: bundle install

      # Verify theme directory
      - name: Verify theme directory
        run: |
          echo "Checking for theme directory..."
          if [ ! -d "./hydejack-theme" ]; then
            echo "Error: hydejack-theme directory is missing!";
            exit 1;
          fi

      # Build the Jekyll site
      - name: Build site
        run: bundle exec jekyll build

      # Deploy the built site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
